I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1577, in script
    
  File "renpy/common/00nvl_mode.rpy", line 380, in do_display
    **display_args)
IOError: Couldn't find file 'sound.footstepsGravelFast.wav'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1577, in script
    
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\ast.py", line 706, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\exports.py", line 1336, in say
    who(what, *args, **kwargs)
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\character.py", line 1139, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "renpy/common/00nvl_mode.rpy", line 380, in do_display
    **display_args)
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\character.py", line 591, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\ui.py", line 295, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\display\core.py", line 2699, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\display\core.py", line 3377, in interact_core
    renpy.audio.audio.periodic()
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\audio\audio.py", line 1023, in periodic
    six.reraise(exc[0], exc[1], exc[2])
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\audio\audio.py", line 1001, in periodic_thread_main
    periodic_pass()
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\audio\audio.py", line 942, in periodic_pass
    c.periodic()
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\audio\audio.py", line 420, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\audio\audio.py", line 72, in load
    rv = renpy.loader.load(fn)
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\loader.py", line 576, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'sound.footstepsGravelFast.wav'.

Windows-8-6.2.9200
Ren'Py 7.3.2.320
VisualNovel 1.0
Sun May 10 02:56:35 2020
